# coding: utf-8

"""
    Discovery API

    The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

    The version of the OpenAPI document: v2
    Created by: http://developer.ticketmaster.com/support/contact-us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ticketmaster_python_sdk import schemas  # noqa: F401


class EventSalesDates(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Event's Sales Dates
    """


    class MetaOapg:
        
        class properties:
            
            
            class presales(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Presale']:
                        return Presale
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Presale'], typing.List['Presale']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'presales':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Presale':
                    return super().__getitem__(i)
        
            @staticmethod
            def public() -> typing.Type['PublicSaleDates']:
                return PublicSaleDates
            __annotations__ = {
                "presales": presales,
                "public": public,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["presales"]) -> MetaOapg.properties.presales: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["public"]) -> 'PublicSaleDates': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["presales", "public", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["presales"]) -> typing.Union[MetaOapg.properties.presales, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["public"]) -> typing.Union['PublicSaleDates', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["presales", "public", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        presales: typing.Union[MetaOapg.properties.presales, list, tuple, schemas.Unset] = schemas.unset,
        public: typing.Union['PublicSaleDates', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EventSalesDates':
        return super().__new__(
            cls,
            *args,
            presales=presales,
            public=public,
            _configuration=_configuration,
            **kwargs,
        )

from ticketmaster_python_sdk.model.presale import Presale
from ticketmaster_python_sdk.model.public_sale_dates import PublicSaleDates
