# coding: utf-8

"""
    Discovery API

    The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

    The version of the OpenAPI document: v2
    Created by: http://developer.ticketmaster.com/support/contact-us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ticketmaster_python_sdk import schemas  # noqa: F401


class PublicSaleDates(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Event's Public Onsales Dates
    """


    class MetaOapg:
        
        class properties:
            endDateTime = schemas.DateTimeSchema
            startDateTime = schemas.DateTimeSchema
            startTBD = schemas.BoolSchema
            __annotations__ = {
                "endDateTime": endDateTime,
                "startDateTime": startDateTime,
                "startTBD": startTBD,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endDateTime"]) -> MetaOapg.properties.endDateTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["startDateTime"]) -> MetaOapg.properties.startDateTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["startTBD"]) -> MetaOapg.properties.startTBD: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["endDateTime", "startDateTime", "startTBD", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endDateTime"]) -> typing.Union[MetaOapg.properties.endDateTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["startDateTime"]) -> typing.Union[MetaOapg.properties.startDateTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["startTBD"]) -> typing.Union[MetaOapg.properties.startTBD, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["endDateTime", "startDateTime", "startTBD", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        endDateTime: typing.Union[MetaOapg.properties.endDateTime, str, datetime, schemas.Unset] = schemas.unset,
        startDateTime: typing.Union[MetaOapg.properties.startDateTime, str, datetime, schemas.Unset] = schemas.unset,
        startTBD: typing.Union[MetaOapg.properties.startTBD, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PublicSaleDates':
        return super().__new__(
            cls,
            *args,
            endDateTime=endDateTime,
            startDateTime=startDateTime,
            startTBD=startTBD,
            _configuration=_configuration,
            **kwargs,
        )
