# coding: utf-8

"""
    Discovery API

    The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

    The version of the OpenAPI document: v2
    Created by: http://developer.ticketmaster.com/support/contact-us/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ticketmaster_python_sdk import schemas  # noqa: F401


class VenueGeneralInfo(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Venue general information
    """


    class MetaOapg:
        
        class properties:
            childRule = schemas.StrSchema
            generalRule = schemas.StrSchema
            __annotations__ = {
                "childRule": childRule,
                "generalRule": generalRule,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["childRule"]) -> MetaOapg.properties.childRule: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["generalRule"]) -> MetaOapg.properties.generalRule: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["childRule", "generalRule", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["childRule"]) -> typing.Union[MetaOapg.properties.childRule, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["generalRule"]) -> typing.Union[MetaOapg.properties.generalRule, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["childRule", "generalRule", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        childRule: typing.Union[MetaOapg.properties.childRule, str, schemas.Unset] = schemas.unset,
        generalRule: typing.Union[MetaOapg.properties.generalRule, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VenueGeneralInfo':
        return super().__new__(
            cls,
            *args,
            childRule=childRule,
            generalRule=generalRule,
            _configuration=_configuration,
            **kwargs,
        )
