# coding: utf-8

"""
    Discovery API

    The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

    The version of the OpenAPI document: v2
    Created by: http://developer.ticketmaster.com/support/contact-us/
"""

from ticketmaster_python_sdk.paths.discovery_v2_events.get import EventSearch
from ticketmaster_python_sdk.paths.discovery_v2_suggest.get import FindSuggest
from ticketmaster_python_sdk.paths.discovery_v2_venues.get import FindVenues
from ticketmaster_python_sdk.paths.discovery_v2_attractions_id.get import GetAttractionDetails
from ticketmaster_python_sdk.paths.discovery_v2_classifications_id.get import GetClassificationDetails
from ticketmaster_python_sdk.paths.discovery_v2_events_id.get import GetEventDetails
from ticketmaster_python_sdk.paths.discovery_v2_events_id_images.get import GetEventImages
from ticketmaster_python_sdk.paths.discovery_v2_classifications_genres_id.get import GetGenreDetails
from ticketmaster_python_sdk.paths.discovery_v2_classifications_segments_id.get import GetSegmentDetails
from ticketmaster_python_sdk.paths.discovery_v2_classifications_subgenres_id.get import GetSubgenreDetails
from ticketmaster_python_sdk.paths.discovery_v2_venues_id.get import GetVenueDetails
from ticketmaster_python_sdk.paths.discovery_v2_attractions.get import SearchAttractions
from ticketmaster_python_sdk.paths.discovery_v2_classifications.get import SearchClassifications
from ticketmaster_python_sdk.apis.tags.v2_api_raw import V2ApiRaw


class V2Api(
    EventSearch,
    FindSuggest,
    FindVenues,
    GetAttractionDetails,
    GetClassificationDetails,
    GetEventDetails,
    GetEventImages,
    GetGenreDetails,
    GetSegmentDetails,
    GetSubgenreDetails,
    GetVenueDetails,
    SearchAttractions,
    SearchClassifications,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: V2ApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = V2ApiRaw(api_client)
